spring:
  #  application:
  #    name:yupao-backend
  datasource:
    druid:
      username: kkh
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: yupi666
#      url: jdbc:mysql://localhost:3306/yupao-backend
      url: jdbc:mysql://62.234.35.31:3306/user_center

  # session失效时间： 1天
  session:
    timeout: 86400
server:
    address: 0.0.0.0
