spring:
  application:
    name:user-center
  datasource:
    druid:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3306/yupi
  # session失效时间： 1天
  session:
    timeout: 86400


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  type-aliases-package: "com.szu.usercenter.pojo"

server:
  port: 8080
  servlet:
    context-path: /api

