spring:
#  application:
#    name:user-center
  datasource:
    druid:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3306/user-center
  # session失效时间： 1天
  session:
    timeout: 86400

