spring:
  application:
    name:yupao-backend
  datasource:
    druid:
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3306/yupi
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # session失效时间： 1天
  session:
    timeout: 86400
    # 默认存储在内存中
    store-type: redis
  profiles:
    active: dev

  # redis配置
  data:
    redis:
      host: localhost
      port: 6379
      database: 1


mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  type-aliases-package: "com.szu.yupao.pojo"

server:
  servlet:
    context-path: /api





# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径,输入http:localhost:8080/api/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs:
    - group: 'default'   #分组名称
      paths-to-match: '/**'   #配置需要匹配的路径,默认为/**
      packages-to-scan: com.szu.yupao    #配置要扫描包的路径,一般配置到启动类所在的包名


